language: objective-c
osx_image: xcode7.3
git:
  submodules: false
branches:
  only:
    - master
script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  include:
    - script: set -o pipefail && script/cibuild | xcpretty
      env: JOB=Xcode
    - script: make spm_test
      env: JOB=SPM
      before_install:
        - make swift_snapshot_install
  exclude:
    - script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681

notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
after_success:
  - bash <(curl -s https://codecov.io/bash)
